worms_life: 200
weapon_ammo:
  Bazooka: 99999
  Mortar: 10
  GreenGrenade: 99999
  RedGrenade: 10
  Banana: 5
  HolyGrenade: 2
  Dynamite: 5
  Bat: 99999
  AirAttack: 2
  Teleportation: 99999
worms:
  -
    - 10
    - 60
  -
    - 20
    - 60
  -
    - 30
    - 60
  -
    - 40
    - 60
  -
    - 50
    - 60
girders:
  -
    - 6
    - 7
    - 20
    - 0
  -
    - 6
    - 17
    - 20
    - 0
  -
    - 6
    - 27
    - 20
    - 0
  -
    - 6
    - 37
    - 20
    - 0
  -
    - 6
    - 47
    - 20
    - 0