worms_life: 200
weapon_ammo:
  Bazooka: 99999
  Mortar: 10
  GreenGrenade: 99999
  RedGrenade: 10
  Banana: 5
  HolyGrenade: 2
  Dynamite: 5
  Bat: 99999
  AirAttack: 100
  Teleportation: 99999
worms:
  -
    - 4
    - 10
  -
    - 10
    - 10
  -
    - 16
    - 10
  -
    - 19
    - 15
  -
    - 50
    - 15
girders:
  -
    - 3
    - 4
    - 8
    - 0
  -
    - 3
    - 10
    - 8
    - 0
  -
    - 6
    - 16
    - 8
    - 0
  -
    - 3
    - 19
    - 8
    - 0
  -
    - 6
    - 50
    - 8
    - 0
