worms_life_to_add: 25

worm_velocity: 3.2
worm_jump_velocity: 7
worm_rollback_velocity: 7
worm_jump_height: 7
worm_rollback_height: 7
weapons_velocity: 13

weapon_radius:
  Bazooka: 2
  Mortar: 2
  GreenGrenade: 2
  RedGrenade: 2
  Banana: 4
  HolyGrenade: 8
  Dynamite: 4
  Bat: 2 #largo del bate
  AirAttackMissile: 2

weapon_damage:
  Bazooka: 50
  Mortar: 50
  GreenGrenade: 30
  RedGrenade: 30
  Banana: 70
  HolyGrenade: 110
  Dynamite: 50
  Bat: 10
  AirAttackMissile: 40