port: 7777

worms_life_to_add: 25
worm_velocity: 1.2
worm_explosion_velocity: 0.5  #proportion of damage received
worm_jump_velocity: 1.6
worm_rollback_velocity: 1.4
worm_jump_height: 5
worm_rollback_height: 3
weapons_velocity: 7
wind_min_velocity: 0.1
wind_max_velocity: 0.5
gravity: -10
air_missiles_separation: 1
worm_height_to_damage: 2
worm_max_height_damage: 25
max_girder_rotation_friction: 45
weapon_radius:
  Bazooka: 2
  Mortar: 2
  GreenGrenade: 2
  RedGrenade: 2
  Banana: 4
  HolyGrenade: 8
  Dynamite: 4
  Bat: 2  #size of the bat
  AirAttackMissile: 2
  MortarFragment: 2
  RedGrenadeFragment: 2
weapon_damage:
  Bazooka: 50
  Mortar: 50
  GreenGrenade: 30
  RedGrenade: 30
  Banana: 70
  HolyGrenade: 110
  Dynamite: 50
  Bat: 10
  AirAttackMissile: 40
  MortarFragment: 10
  RedGrenadeFragment: 10
weapon_fragments:
  Mortar: 6
  RedGrenade: 6
  AirAttack: 6
