worms_life_to_add: 25
worm_velocity: 2.2
worm_jump_velocity: 7
worm_rollback_velocity: 7
worm_jump_height: 7
worm_rollback_height: 7
weapons_velocity: 13
weapon_radius:
  Bazooka: 2
  Mortar: 2
  GreenGrenade: 2
  RedGrenade: 2
  Banana: 4
  HolyGrenade: 8
  Dynamite: 4
  Bat: 2
  AirAttackMissile: 2
  MortarFragment: 2
  RedGrenadeFragment: 2
weapon_damage:
  Bazooka: 50
  Mortar: 50
  GreenGrenade: 30
  RedGrenade: 30
  Banana: 70
  HolyGrenade: 110
  Dynamite: 50
  Bat: 10
  AirAttackMissile: 40
  MortarFragment: 10
  RedGrenadeFragment: 10
weapon_fragments:
  Mortar: 6
  RedGrenade: 6
  AirAttack: 6
