background_image: background0.jpg
worms_life: 200
weapon_ammo:
  Bazooka: 50
  Mortar: 50
  GreenGrenade: 50
  RedGrenade: 50
  Banana: 5
  HolyGrenade: 2
  Dynamite: 5
  Bat: 50
  AirAttack: 50
  Teleportation: 50
worms:
  -
    - 4
    - 10
  -
    - 10
    - 10
  -
    - 16
    - 10
  -
    - 19
    - 15
  -
    - 50
    - 15
girders:
  -
    - 6
    - 4
    - 8
    - 10
  -
    - 6
    - 10
    - 8
    - 20
  -
    - 6
    - 16
    - 8
    - 30
  -
    - 6
    - 19
    - 8
    - 40
  -
    - 6
    - 50
    - 8
    - 0
