worms_life: 100
weapon_ammo:
  Bazooka: -1
  Mortar: 10
  GreenGrenade: -1
  RedGrenade: 10
  Banana: 5
  HolyGrenade: 2
  Dynamite: 5
  Bat: -1
  AirAttack: 2
  Teleportation: -1
worms:
  -
    - 5
    - 80
  -
    - 13
    - 77
  -
    - 15
    - 77
  -
    - 4
    - 75
  -
    - 12
    - 72
  -
    - 15
    - 72
  -
    - 17
    - 74
  -
    - 16
    - 73
  -
    - 12
    - 72
girders:
  -
    - 3
    - 5
    - 79
    - 0
  -
    - 6
    - 14
    - 77
    - 0
  -
    - 3
    - 4
    - 74
    - 140
  -
    - 6
    - 15
    - 70
    - 0
  -
    - 3
    - 12
    - 70
    - 0
  -
    - 6
    - 16
    - 71
    - 80