background_image: background0.jpg
worms_life: 200
weapon_ammo:
  Bazooka: 10
  Mortar: 17
  GreenGrenade: 15
  RedGrenade: 11
  Banana: 12
  HolyGrenade: 2
  Dynamite: 5
  Bat: 24
  AirAttack: 19
  Teleportation: 28
worms:
  -
    - 4.552637577056885
    - 9.697680473327637
girders:
  -
    - 6
    - 4
    - 8
    - 0
  -
    - 6
    - 7
    - 8
    - 0
  -
    - 6
    - 10
    - 8
    - 0
  -
    - 6
    - 13
    - 8
    - 0
  -
    - 6
    - 16
    - 8
    - 0